### ISSUE TITLE
NextJS Test Fails: npm run test.nextjs.chromium

### ISSUE THREAD

**Issue by DanielBailey-web** [QwikDev/partytown#153]
What I did
`git clone https://github.com/BuilderIO/partytown.git`
`npm install`
`npm run test.nextjs.chromium`

## My Environment
```
Operating System:
      Platform: linux
      Arch: x64
      Version: #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022
    Binaries:
      Node: 14.18.1
      npm: 8.1.4
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2
``` 
## Output
```
~/Desktop/party-town-test/partytown$ npm run test.nextjs.chromium

> @builder.io/partytown@0.5.2 test.nextjs.chromium
> cd tests/nextjs && npm i && playwright test --config playwright.nextjs.ts --browser=chromium


up to date, audited 20 packages in 2s

2 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
Using config at /home/danie/Desktop/party-town-test/partytown/tests/nextjs/playwright.nextjs.ts

Running 1 test using 1 worker

  ✘  [chromium] › nextjs.spec.ts:3:1 › nextjs (30s)


  1) [chromium] › nextjs.spec.ts:3:1 › nextjs ======================================================

    Timeout of 30000ms exceeded.

    Pending operations:
      - page.waitForSelector at nextjs.spec.ts:6:14

    page.waitForSelector: Target closed
    =========================== logs ===========================
    waiting for selector ".completed" to be visible
    ============================================================

      4 |   await page.goto('/');
      5 |
    > 6 |   await page.waitForSelector('.completed');
        |              ^
      7 |
      8 |   const h1 = page.locator('h1');
      9 |   await expect(h1).toHaveText('Next.js with 🎉');

        at /home/danie/Desktop/party-town-test/partytown/tests/nextjs/nextjs.spec.ts:6:14

  Slow test file: [chromium] › nextjs.spec.ts (30s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    [chromium] › nextjs.spec.ts:3:1 › nextjs =======================================================
```

**Comment by steve8708** [comment]
hey @DanielBailey-web - we've just created an issue template, could you update your issue here to provide all the information the template asks for? it'll help us look into your issue https://github.com/BuilderIO/partytown/issues/new?assignees=&labels=&template=bug_report.md&title=

pasting below to make things easier:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Reproduction link**
Please include a link to a Stackblitz or Codesandbox reproducing the issue. We will need to see the issue reproduced with hand-written code - we can't debug giant minified third party scripts directly. If you do not include a clean and simple reproduction of your issue, we won't be able to look into it until you do.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
