### ISSUE TITLE
Party Town Breaks Adsense even if its not marked as text/partytown

### ISSUE THREAD

**Issue by naveedahmed1** [QwikDev/partytown#169]
I recently added Party Town to one of my websites.

I am also using Google Adsense on my website, and its throwing below error:

```
partytown-sandbox-sw.js?v=0.5.2:516 Web Worker Error ErrorEvent {isTrusted: true, message: "Uncaught TypeError: Cannot read properties of undefined (reading '$location$')", filename: 'http://localhost/~partytown/debug/partytown-ww-sw.js?v=0.5.2', lineno: 1656, colno: 118, …}
worker.onerror @ partytown-sandbox-sw.js?v=0.5.2:516
error (async)
(anonymous) @ partytown-sandbox-sw.js?v=0.5.2:516
Promise.then (async)
(anonymous) @ partytown-sandbox-sw.js?v=0.5.2:506
(anonymous) @ partytown-sandbox-sw.js?v=0.5.2:520
partytown-ww-sw.js?v=0.5.2:1656 Uncaught TypeError: Cannot read properties of undefined (reading '$location$')
    at receiveMessageFromSandboxToWorker (partytown-ww-sw.js?v=0.5.2:1656:118)
```

If I remove adsense script from the website, it doesn't throw this error. So, I assume thatr Party Town is somehow interacting with scripts that are not even marked as `text/partytown`.

**Comment by steve8708** [comment]
hey @naveedahmed1 - we've just created an issue template, could you update your issue here to provide all the information the template asks for? it'll help us look into your issue https://github.com/BuilderIO/partytown/issues/new?assignees=&labels=&template=bug_report.md&title=

pasting below to make things easier:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Reproduction link**
Please include a link to a Stackblitz or Codesandbox reproducing the issue. We will need to see the issue reproduced with hand-written code - we can't debug giant minified third party scripts directly. If you do not include a clean and simple reproduction of your issue, we won't be able to look into it until you do.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by AlphaBeta906** [comment]
I have made a reproduction of this bug.

Here is the repo: [Repo](https://github.com/AlphaBeta906/Testing)
Here is the site: [Site](https://friendly-hotteok-c6f7f6.netlify.app)

**Comment by harshit-kathuria** [comment]
@AlphaBeta906 We are facing issues while moving adsense script to web worker with Partytown. However, when using Partytown, we're facing a CORS error that is not present when the script is called directly in the main thread.
**Error**
<img width="863" alt="Screenshot 2024-01-16 at 2 42 34 PM" src="https://github.com/BuilderIO/partytown/assets/114906077/8aea2269-46c2-489d-9939-a4e66bf9a443">


Any suggestions or insights on this, considering that it seems to be working for you.

**Comment by RiodeJaneiroo** [comment]
@harshit-kathuria i have the same issues
