### ISSUE TITLE
CWE-95 - Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')

### ISSUE THREAD

**Issue by RezaRahmati** [QwikDev/partytown#279]
Hi

Veracode is reporting two very high severity CWE-95 issue on the lib, in partytwon-ww.atomic.js line 686 and partytown-ww.sw.js line 678
(lib is directly used in gatsby)

The reference to the issue https://cwe.mitre.org/data/definitions/95.html

![image](https://user-images.githubusercontent.com/10086092/194607833-f6b82f7d-ac64-4456-a7dd-3ebd52005852.png)

![image](https://user-images.githubusercontent.com/10086092/194608870-e41eefc8-291c-440d-8754-f993993cd289.png)

**Comment by graysonhicks** [comment]
Seeing the same thing on a site:

![image](https://user-images.githubusercontent.com/16200795/212117540-8b75b508-c4fd-404c-870e-df165fb2c1dc.png)

I believe it _may_ be a false positive since that function is calling `scriptContent` which should always be controlled by the user and not vulnerable to injection, but I could definitely be wrong!
