### ISSUE TITLE
Running scripts injected by GTM without a url/src on main thread

### ISSUE THREAD

**Issue by michaelbourne** [QwikDev/partytown#304]
`loadScriptsOnMainThread`  appears to only work via URL, not ID like documented. 

It looks like this line is only checking the URL of scripts, not the ID: https://github.com/BuilderIO/partytown/blob/main/src/lib/web-worker/worker-script.ts#L30

Partytown.j grabs script elements with https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement and `HTMLScriptElement` inherits properties from `Element`, so `id` is available as a property.

It seems like we need to amend that check to something along the lines of this, but I'm not sure how a property from `HTMLScriptElement` gets sent to this function.

```
          const shouldExecuteScriptViaMainThread = config.loadScriptsOnMainThread.some(scriptIdentifier => 
            scriptIdentifier === url || scriptIdentifier === id
          )
```

Sadly I'm fairly new to TS and I'm stuck at that point.

_Originally posted by @michaelbourne in https://github.com/BuilderIO/partytown/issues/244#issuecomment-1319260999_

**Comment by kriticalflare** [comment]
Having this implemented would open us up to the possibility of loading GTM through partytown and at the same time selectively opting certain scripts that are UI heavy and not ideal for partytown, being loaded normally. 

For now i am loading GTM normally ( not through partytown ) and have appended `type="text/partytown"` to the compatible scripts in the gtm console in order to opt them into partytown.

This approach works fine but GTM itself has a heavy impact on performance and i would like to run GTM through partytown. 

I also took a stab at implementing this but was unable to do so. @adamdbradley it would be nice if you could give some pointers wrt implementation
