### ISSUE TITLE
[✨] Partytown support and stable release plans

### ISSUE THREAD

**Issue by DzmVasileusky** [QwikDev/partytown#419]
### Is your feature request related to a problem?

@adamdbradley 
Partytown is a great idea which is currently badly supported and still is in 0.x version.
I know that you are maintaining a lot of different projects so no offending here just a desire to know what plans do you have on partytown to let people understand if they can use it in enterprise projects or not.

### Describe the solution you'd like

Strategy of partytown development:
1. who will be working on it - maybe you need a team to help
2. who will be supporting it - there are 85 issues and PRs fixing some of them which got review in half a year
3. approximate stable release date or at least position in queue of builder.io projects

### Describe alternatives you've considered

If it is hard to answer with solid strategy and dates, maybe you can just leave some notes about your plans on it like:
"Don't have time on it and don't know when it will be prioritised"
or
"Waiting for collaborators to help me with this"
or
"I am planning to finish with Qwik which will take around 1 year then maybe work on this"

**Comment by mhevery** [comment]
We agree that Partytown is a great idea and is badly needed by the world. However, here are a few things to consider as to why the support for Partytown has not been as high as we would like...

1. Partytown emulates `main` thread on the `web-worker` thread. As such it is easy to get 90% working, but the amount of work required to get close to 100% is exponential. It is very hard (time-consuming) to debug third-party code that is minified and has lots of try/catch which just eat exceptions (as third-party code does not want to pollute the console with errors)
2. Lack of good reproductions. There are a lot of "it-does-not-work" but no easy reproduction issues filed. We just don't have time to do anything about it. The only way we can help is to get a clean small repro. Otherwise, we can't do much.
3. I think the way out of this is to have third-party developers to self-certify that they work on Paratytown as they are in the best position to know what is not working and why, and then either create a small repro for us to fix, or change their code in a way which works with partytown.
4. And as always, with OSS software at the end of the day someone needs to pay for the engineer's time. Without a dedicated person working on it, it is difficult to make progress. For a startup such as builder.io there are higher priority things which we need to focus on.

**Comment by DzmVasileusky** [comment]
@mhevery Not sure what are your team policy is but is it possible to let web volunteers to join the partytown development?
The code isn't very complicated but when I created a PR it was reviewed in a half a year. If more people would have an access to CR it would be much faster.
